apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-service
  template:
    metadata:
      labels:
        app: list-service
    spec:
      containers:
      - name: list-service
        image: ubevk/list-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/list_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"