version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: shopsync-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      sh -c "docker-entrypoint.sh postgres &
      sleep 5;
      psql -U postgres -c 'CREATE DATABASE user_db;';
      psql -U postgres -c 'CREATE DATABASE list_db;';
      psql -U postgres -c 'CREATE DATABASE recipe_db;';
      wait"
    deploy:
      resources:
        limits:
          memory: 256M

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: shopsync-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xms128M -Xmx128M"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: shopsync-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
    deploy:
      resources:
        limits:
          memory: 512M
  
  user-service:
    image: ${DOCKERHUB_USERNAME}/user-service:latest
    container_name: user-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - db
      - kafka

  recipe-service:
    image: ${DOCKERHUB_USERNAME}/recipe-service:latest
    container_name: recipe-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recipe_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
      - kafka

  gateway-service:
    image: ${DOCKERHUB_USERNAME}/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8083
      - RECIPE_SERVICE_URL=http://recipe-service:8084
      - LIST_SERVICE_URL=http://list-service:8082
    depends_on:
      - user-service
      - recipe-service
  notification-service:
    platform: linux/arm64
    image: ${DOCKERHUB_USERNAME}/notification-service:latest
    container_name: notification-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
      - db

  list-service:
    image: ${DOCKERHUB_USERNAME}/list-service:latest
    container_name: list-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/list_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - db
      - kafka
